# Generated by Django 2.2 on 2022-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cateogry Name')),
                ('slug', models.SlugField(help_text='unique value for product page url, created from name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keyword', models.CharField(max_length=255, verbose_name='Meta Keyword')),
                ('meta_description', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='unique value for product page url, created from name', unique=True, verbose_name='Slug')),
                ('brand', models.CharField(max_length=200, verbose_name='Brand Name')),
                ('sku', models.CharField(max_length=50, verbose_name='Sku')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Old Price')),
                ('image', models.ImageField(upload_to='', verbose_name='Product Image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('description', models.TextField(verbose_name='Description')),
                ('meta_description', models.CharField(max_length=250, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Meta Keywords')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('categories', models.ManyToManyField(to='catalog.Category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created'],
            },
        ),
    ]
